import { DEFAULT_HEIGHT, DEFAULT_WIDTH } from "../sizes/GameSizes";
import { RESULTBAR_HEIGHT, RESULTBAR_WIDTH } from "../sizes/ResultBarSize";

export const RESULTBAR_POSITION_X = DEFAULT_WIDTH / 2 - RESULTBAR_WIDTH / 2;
export const RESULTBAR_POSITION_Y = DEFAULT_HEIGHT / 2 - RESULTBAR_HEIGHT / 2;