export * from './sizes/GameSizes'
export * from './params/BirdParams'
export * from './params/ObstacleParams'
export * from './positions/StartBtnPosition'
export * from './sizes/ResultBarSize'
export * from './positions/ResultBarPosition'
export * from './positions/ObstaclePosition'